### ISSUE TITLE
Branch is not taken into account in `update` command

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-monitor#100]
When I have a Home installed on a custom branch,
Then I try to update with `cozy-monitor update home`

Result:
```
cozy-monitor update home
info - Updating home...
error - An error occured:
error - Update failed for home.
[Error: Error: Command failed: From https://github.com/cozy/cozy-home
 * branch            master     -> FETCH_HEAD
]
```

And the application is not updated.

**Comment by clochix** [comment]
@jsilvestre would you mind give the patch a try and close this ticket? Thanks for reporting and to @poupotte for her quick fix ☺

**Comment by poupotte** [comment]
@jsilvestre , it works for you ?

**Comment by frankrousseau** [comment]
@poupotte It doesn't work when a full stack update is performed.

**Comment by poupotte** [comment]
@frankrousseau , it doesn't take branch or update stack doesn't work ? Have you some errors ?
