### ISSUE TITLE
Wrong application permissions after reinstall-missing-app

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-monitor#114]
Application token is now stored in `Access` document instead of `Application` : https://github.com/cozy/cozy-monitor/blob/master/lib/application.coffee#L339

**Comment by clochix** [comment]
Can we close this one @poupotte ?

**Comment by poupotte** [comment]
I want test it once published but 7f25c0d should fixed it :)

**Comment by poupotte** [comment]
This issue should be fixed
