### ISSUE TITLE
Error during npm install leads to a blocked state

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-monitor#119]
# How to reproduce
```
$ sudo cozy-monitor install -r https://github.com/bnjbvr/kresus -b build kresus
info - Install started for kresus...
```
The process then gets stuck.

## Controller's logs:
https://pastebin.mozilla.org/8855456

## Versions:
```
Cozy Stack:
controller: 2.0.38
data-system: 2.1.6
proxy: 2.1.12
monitor: 1.2.33
```

**Comment by bnjbvr** [comment]
On my machine, cozy-monitor starts the install, but nothing happens afterwards. I get stuck with `info - Install started for kresus...`.

**Comment by bnjbvr** [comment]
So after some build changes I've done, the build dependencies were included in the `devDependencies` section of the package.json file. The `npm install` done on Cozy passes `--production` to the command line, so it doesn't install those. I am moving them back into the package dependencies right now. However, it seems like some error message isn't getting passed back from npm to the cozy monitor, here (see previous comment).

**Comment by clochix** [comment]
@jsilvestre your pastebin has already expired, could you paste the logs here?

**Comment by marmeladema** [comment]
Same here, i followed the debian guide: https://docs.cozy.io/en/host/install/install-on-debian.html
At some point, the install fails for some app, and then, every following app will also fail installing and it takes each time, a few minutes (~5minutes) BY app for cozy to understand that something has gone bad and print 

> error - An error occured:
> error - Install failed for photos.
> [Error: Error: Expected application not listed in database after installation.]

At some point, i killed the installer (ctrl+c) and try uninstall by hand each app that failed
> cozy-monitor uninstall photos

And it gets stuck for ever doing nothing, printing only
> info - Uninstall started for photos...


I checked the logs in /usr/local/var/log/cozy/photos.log-backup and in /usr/local/var/log/cozy/photos-err.log-backup and there is only those lines in loop:

> Error: Cannot find module 'mime-db'
>     at Function.Module._resolveFilename (module.js:325:15)
>     at Function.Module._load (module.js:276:25)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (/usr/local/cozy/apps/photos/node_modules/americano/node_modules/express/node_modules/accepts/node_modules/mime-types/index.js:15:10)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Module.require (module.js:353:17)
> module.js:327
>     throw err;

I'm using a regular debian jessie but with jessie-backports in my sources.list, don't know if that could be related.
I hope all those info will help, at the moment, debian packages are totally unusable.
I did not try installing eveything by hand though.

Cheers

P.S : i don't want to start a flamewar here, but what were the pros/cons for choosing node.js ecosystem to develop this kind of software ? It seems like a weird choice to me :)

**Comment by clochix** [comment]
Hi @marmeladema,

Could we move both of your requests to [our forum](https://forum.cozy.io). It's a better place for support requests and technology discussions ;-)
