### ISSUE TITLE
Start command is broken

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-monitor#56]
Start command doesn't give acces rights anymore. So the application cannot work properly.

**Comment by poupotte** [comment]
@frankrousseau, I can't reproduce this problem. To be sure, this issue concerns classic start command (stack or user application) or start-standalone (wich start application without controller) ?

**Comment by frankrousseau** [comment]
It's about classic start command. I'm working on something else right now. I will try again later.

**Comment by poupotte** [comment]
@frankrousseau , any news with the new monitor ?

**Comment by frankrousseau** [comment]
Let's close it. I will reopen it if I meet the problem again. Thank you for asking.
