### ISSUE TITLE
cozy-monitor status errors

### ISSUE THREAD

**Issue by aenario** [cozy/cozy-monitor#78]
Improve errors for cozy-monitor status 

`Cant get app list` is not accurate enough, it should debug the following cases : 
- couchdb.login doesnt exists / wrong chmod
- controller doesnt have proper token vs DS
- ect ...

**Comment by poupotte** [comment]
Error logs for status command should be improved in next version :)

**Comment by clochix** [comment]
I stopped the data-system, and the message is much clearer now:
```
error - The Cozy Data System looks not started
error - The Cozy Home looks not started
error - Cannot retrieve apps
error - An error occured:
error - Cannot display status
[Error: Error: Parsing error : Unexpected token I, body= 
 Internal Server Error]
```

Thanks @poupotte :-)
