### ISSUE TITLE
Remove postfix & couch from "cozy-monitor status"

### ISSUE THREAD

**Issue by nledez** [cozy/cozy-monitor#83]
Hello,

I think postfix can remove from "cozy-monitor status". Another MTA could be used.

Couch may be removed too.

**Comment by poupotte** [comment]
@nledez , why do you want remove couchDB ?
In my mind, cozy-monitor status it's the first command for debugging. Sometimes, couchDB is stoppped (because of disk problem as an example). Thus, status command allows to see couchDB problem directly.

**Comment by frankrousseau** [comment]
+1 with @poupotte

**Comment by clochix** [comment]
I agree that `cozy-monitor` is an essential command to diagnose server problems, so please don't remove useful information from it ;-)
In fact, the Postfix check is just checking that something is listening on port 25, so the result will be the same in Debian with Exim. I suggest to just rename the displayed value to `mta`.

**Comment by frankrousseau** [comment]
+1 with @clochix

**Comment by clochix** [comment]
Thanks @poupotte ☺
@nledez we have renamed postfix to mta, and kept CouchDB, is it ok for you ?

**Comment by nledez** [comment]
Yes, thanks!
