### ISSUE TITLE
Give an option for setting the installation timeout

### ISSUE THREAD

**Issue by bnjbvr** [cozy/cozy-monitor#85]
Users complain that sometimes, Kresus is quite long to install on Raspberry Pi. As a matter of fact, it'd be nice if the utility line had an option to either allow setting the installation timeout, or even better, just remove this timeout.

**Comment by fflorent** [comment]
Looks like it should be closed, right? :)

**Comment by frankrousseau** [comment]
Yep @bnjbvr. Is it fixed?

**Comment by bnjbvr** [comment]
Maybe @ZeHiro could chime in here, as he uses a RPi2, if I remember correctly?

**Comment by ZeHiro** [comment]
Didn't try yet, and yes my cozy is on a PI2. I'll try it out.

**Comment by clochix** [comment]
Hello @ZeHiro, have you find time to give this a try ?

**Comment by ZeHiro** [comment]
@clochix, it works fine fir 'install' command. But it misses for 'update' (it appens when npm cache has to updated). Thank you

**Comment by clochix** [comment]
Thanks for the tests @ZeHiro :-)
@poupotte would you mind having a look at this ?

**Comment by clochix** [comment]
@poupotte should I open another issue for adding a timeout option for update command?

**Comment by poupotte** [comment]
I opened a ticket for update : https://github.com/cozy/cozy-monitor/issues/106. So I close this issue.
