### ISSUE TITLE
Add a command to add in database application installed on disk

### ISSUE THREAD

**Issue by poupotte** [cozy/cozy-monitor#99]
Useful for Cozy initialisation.

**Comment by clochix** [comment]
I would really really like to have this feature, for example to be able to install whiteout mail into Cozy (the installation is always marked broken, even when the application works).

**Comment by poupotte** [comment]
[Reinstall-missing-app](https://github.com/cozy/cozy-monitor/blob/master/lib/main.coffee#L330) allows to install application already installed on disk. This function is use for cozy relocation as an example.
